# Generated by Django 5.1 on 2024-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_statistic_dataitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
